# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'

## Base settings ##
url:  #the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: /
title: Travel AI
description: > #this means to ignore newlines until "nav_lists:"
    Learning with Machines

nav_lists:
  - titles:
      en: About
    url: /blog/about.html



paths:
  base: /blog
  home: /
  all:  /blog/all.html
  # rss:  /feed.xml

## GitHub repository (if the site is hosted by GitHub) ##
repository: namanuiuc/namanuiuc.github.io
repository_tree: master

## Language & timezone ##
lang: en # the language of your site, eg: en(English), zh(简体中文), zh-Hans(简体中文), zh-Hant(繁體中文)
timezone: America/Chicago

## Author & social ##
author:
  name: "Naman Shukla"
  email: naman@deepair.io
  facebook:  naman shukla #your Facebook username
  twitter: namanatulshukla
  github:  namanuiuc
  # googleplus:
  # weibo: 
  # douban: 
  linkedin:  shuklanaman #your Linkedin username

## Comment system (Disqus) ##
disqus:
  shortname: Naman #the Disqus shortname for the site

# Google Analytics ##
ga_tracking_id: G-832KTPQ33M #Google analytics id for the site

## Reading quantity (LeanCloud) ##
# leancloud:
#   app_id: 
#   app_key: 
#   app_class: 

mathjax: true

## Paginate ##
paginate: 7
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: html # text | html

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

## Plugins ##
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji
